# Generated by Django 5.2.17 on 2026-09-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(blank=True, help_text='OPIS Truckstop ID from CSV', null=True, unique=True)),
                ('name', models.CharField(help_text='Station or brand name', max_length=255)),
                ('address', models.CharField(help_text='Street address', max_length=255)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='Two-letter US state code', max_length=10)),
                ('price_per_gallon', models.DecimalField(db_index=True, decimal_places=3, help_text='Retail diesel price per gallon in USD', max_digits=6)),
                ('latitude', models.FloatField(db_index=True, help_text='Geographic latitude coordinate')),
                ('longitude', models.FloatField(db_index=True, help_text='Geographic longitude coordinate')),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_station_coords')],
            },
        ),
    ]
