# Generated by Django 5.2.17 on 2026-09-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='OPIS Truckstop ID from CSV', null=True),
        ),
    ]
